### ISSUE TITLE
boxes gone from atlas

### ISSUE THREAD

**Issue by stackfull** [box-cutter/centos-vm#25]
was this intentional?

**Comment by misheska** [comment]
Yes.  Going forward, box-cutter will be template source only.  Pull requests will still be vetted and built privately, but there will no longer be public box binaries posted to atlas/vagrantcloud.

**Comment by stackfull** [comment]
I probably shouldn't have based so many vagrant environments on them then. I didn't realise boxes would go missing. It's like npm all over again!

**Comment by misheska** [comment]
Sorry about that-I just don't have the resources to continue maintaining them on my own now that I have transitioned to a new job role and am not supporting a team with these boxes.

Your next best bet would be the chef boxes on atlas.

**Comment by stackfull** [comment]
Totally understand. Your packer scripts have saved me hours of work, so thanks very much. I don't think I'll be relying on atlas again though, I'll just host base boxes locally.
